### ISSUE TITLE
Decide reference client

### ISSUE THREAD

**Issue by mxafi** [mxafi/ft_irc#4]
We should decide which irc client to use as a reference

**Comment by mxafi** [comment]
I've found irssi, it's a command line IRC client that seems to be quite solid and be easy to test with.

https://irssi.org/

**Comment by mxafi** [comment]
I've found WeeChat, it's a command line IRC client with lots of features.

https://weechat.org/

**Comment by liocle** [comment]
> I've found irssi, it's a command line IRC client that seems to be quite solid and be easy to test with.
> 
> https://irssi.org/

For good old time nostalgia, mIRC would have been great, but I have always heard great stuff about irssi.... I would opt for this one !

**Comment by mxafi** [comment]
Spoke with @djames9, he approved irssi to be used as a reference as well.

Let's proceed with irssi :)
