### ISSUE TITLE
SEGFAULT to investigate

### ISSUE THREAD

**Issue by liocle** [mxafi/ft_irc#41]
(I tried to repeat it, and it didnt segfault. I am not sure what is the context information that I am missing below)

**Context:**
I was running a session of IRSSI that I kept alive between multiple re-make of our server. I initiated successfully to chat with another client in one session.  Following that, I modified the code, and relaunched the server. Meanwhile Irssi connection to the other user (lets say between **toto** and **tata**) was not closed, and the user **tata** was not exisiting anymore. I reconnected with **toto**, and tried to message the non existing **tata** and got this:

Debug: Message::deserialize_: got prefix_:
Debug: Message::setCommand_: got command_: PRIVMSG
Debug: Message::deserialize_: got command_: PRIVMSG
Debug: last parameter was empty
Debug: Message::deserialize_: got parameters_:
Debug: TATA
Debug: :sjdkfj
Debug: server received message from client on fd 5: PRIVMSG TATA :sjdkfj
Debug: Message is ::sjdkfj to TATA
=================================================================
==28384==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee71c82f9 at pc 0x000108ea8200 bp 0x7ffee71c5990 sp 0x7ffee71c5128
WRITE of size 8 at 0x7ffee71c82f9 thread T0
    #0 0x108ea81ff in wrap_memmove (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1e1ff)
    #1 0x7fff66b6491d in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long) (libc++.1.dylib:x86_64+0x391d)
    #2 0x108a41037 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) string:2538
    #3 0x108a3bb93 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator+=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) string:976
    #4 0x108a3baf4 in irc::Client::appendToSendBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) Client.cpp:117
    #5 0x108a53f89 in irc::Command::actionPrivmsg(irc::Client&) Command.cpp:294
    #6 0x108a99317 in irc::Command::$_7::operator()(irc::Command*, irc::Client&) const Command.cpp:38
    #7 0x108a99229 in decltype(std::__1::forward<irc::Command::$_7&>(fp)(std::__1::forward<irc::Command*>(fp0), std::__1::forward<irc::Client&>(fp0))) std::__1::__invoke<irc::Command::$_7&, irc::Command*, irc::Client&>(irc::Command::$_7&&&, irc::Command*&&, irc::Client&&&) type_traits:4361
    #8 0x108a98fe5 in void std::__1::__invoke_void_return_wrapper<void>::__call<irc::Command::$_7&, irc::Command*, irc::Client&>(irc::Command::$_7&&&, irc::Command*&&, irc::Client&&&) __functional_base:349
    #9 0x108a98e5e in std::__1::__function::__alloc_func<irc::Command::$_7, std::__1::allocator<irc::Command::$_7>, void (irc::Command*, irc::Client&)>::operator()(irc::Command*&&, irc::Client&) functional:1527
    #10 0x108a92c08 in std::__1::__function::__func<irc::Command::$_7, std::__1::allocator<irc::Command::$_7>, void (irc::Command*, irc::Client&)>::operator()(irc::Command*&&, irc::Client&) functional:1651
    #11 0x108ab6751 in std::__1::__function::__value_func<void (irc::Command*, irc::Client&)>::operator()(irc::Command*&&, irc::Client&) const functional:1799
    #12 0x108a44d72 in std::__1::function<void (irc::Command*, irc::Client&)>::operator()(irc::Command*, irc::Client&) const functional:2347
    #13 0x108a43321 in irc::Command::execute(irc::Client&) Command.cpp:62
    #14 0x108a42ac1 in irc::Command::parseCommand(irc::Message const&, irc::Client&) Command.cpp:95
    #15 0x108a42465 in irc::Command::Command(irc::Message const&, irc::Client&, std::__1::map<int, irc::Client, std::__1::less<int>, std::__1::allocator<std::__1::pair<int const, irc::Client> > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, long&) Command.cpp:53
    #16 0x108a42c48 in irc::Command::Command(irc::Message const&, irc::Client&, std::__1::map<int, irc::Client, std::__1::less<int>, std::__1::allocator<std::__1::pair<int const, irc::Client> > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, long&) Command.cpp:51
    #17 0x108b95434 in irc::Server::loop() Server.cpp:221
    #18 0x108b6a888 in main main.cpp:92
    #19 0x7fff6993a3d4 in start (libdyld.dylib:x86_64+0x163d4)

Address 0x7ffee71c82f9 is located in stack of thread T0 at offset 345 in frame
    #0 0x108b6955f in main main.cpp:66

  This frame has 3 object(s):
    [32, 56) 'ref.tmp' (line 74)
    [96, 232) 'server' (line 88)
    [304, 328) 'agg.tmp' <== Memory access at offset 345 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1e1ff) in wrap_memmove
Shadow bytes around the buggy address:
  0x1fffdce39000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdce39010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdce39020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdce39030: 00 00 00 00 f1 f1 f1 f1 f8 f8 f8 f2 f2 f2 f2 f2
  0x1fffdce39040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1fffdce39050: 00 f2 f2 f2 f2 f2 f2 f2 f2 f2 00 00 00 f3 f3[f3]
  0x1fffdce39060: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdce39070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdce39080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdce39090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdce390a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==28384==ABORTING
make: *** [run] Abort trap: 6

**Comment by mxafi** [comment]
Haven't seen this happen again, not reproducable.
